CREATE_USR_MEAL_TABLE = """
CREATE TABLE IF NOT EXISTS USR_MEAL (
    Id INTEGER PRIMARY KEY,
    USER_Id INTEGER NOT NULL,
    CreationDate TEXT NOT NULL,
    CreationTime TEXT NOT NULL,
    HourPeriod TEXT NOT NULL,
    Title TEXT NOT NULL,
    Score INTEGER NOT NULL,
    FOREIGN KEY (USER_Id) REFERENCES USERS (Id) ON DELETE CASCADE
);
"""

CREATE_MEAL_FOODS_TABLE = """
CREATE TABLE IF NOT EXISTS MEAL_FOODS (
    Id INTEGER PRIMARY KEY,
    USR_MEAL_ID INTEGER NOT NULL,
    FOODS_ID INTEGER NOT NULL,
    portionEaten REAL NOT NULL,
    FOREIGN KEY (USR_MEAL_ID) REFERENCES USR_MEAL (Id) ON DELETE CASCADE,
    FOREIGN KEY (FOODS_ID) REFERENCES FOODS (Id) ON DELETE CASCADE
);
"""

SELECT_MEALS_BY_USER_TODAY = """
SELECT Id, CreationDate, CreationTime, HourPeriod, Title, Score FROM USR_MEAL
WHERE USER_Id = ? AND CreationDate LIKE ?;
"""

SELECT_FOODS_BY_MEAL = """
SELECT FOODS.Id, FOODS.Name, FOODS.PortionSize, FOODS.Calories, FOODS.TotalFat,
       FOODS.SaturatedFat, FOODS.Sodium, FOODS.TotalCarbs, FOODS.DietaryFiber,
       FOODS.Sugars, FOODS.Proteins, FOODS.Cholesterol, MEAL_FOODS.portionEaten
FROM MEAL_FOODS
JOIN FOODS ON MEAL_FOODS.FOODS_ID = FOODS.Id
WHERE MEAL_FOODS.USR_MEAL_ID = ?;
"""

SELECT_MEAL_BY_ID = """
SELECT Id, USER_Id, CreationDate, CreationTime, HourPeriod, Title, Score FROM USR_MEAL
WHERE Id = ?;
"""

SELECT_USER_MEALS_PAGINATED = """
SELECT Id, USER_Id, Title, Score, CreationDate, CreationTime, HourPeriod
FROM USR_MEAL
WHERE USER_Id = ?
ORDER BY datetime(CreationDate || ' ' || CreationTime) DESC
"""

SELECT_TOTAL_MEALS_COUNT = """
SELECT COUNT(*)
FROM USR_MEAL
WHERE USER_Id = ?
"""