CREATE_EXERCISES_TABLE = """
CREATE TABLE IF NOT EXISTS EXERCISES (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Type TEXT NOT NULL,
    Muscle TEXT NOT NULL,
    Equipment TEXT NOT NULL,
    Difficulty TEXT NOT NULL,
    Instructions TEXT NOT NULL
);
"""

CREATE_EXERCISE_SETS_TABLE = """
CREATE TABLE IF NOT EXISTS EXERCISE_SETS (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Exercise_Id INTEGER NOT NULL,
    Sets INTEGER NOT NULL,
    Reps INTEGER NOT NULL,
    SetOrder INTEGER NOT NULL,
    FOREIGN KEY (Exercise_Id) REFERENCES EXERCISES(Id)
);
"""

CREATE_WORKOUTS_TABLE = """
CREATE TABLE IF NOT EXISTS WORKOUTS (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    Color TEXT,
    Type TEXT,
    Description TEXT
);
"""

CREATE_WORKOUT_EXERCISE_SETS_TABLE = """
CREATE TABLE IF NOT EXISTS WORKOUT_EXERCISE_SETS (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Workout_Id INTEGER NOT NULL,
    Exercise_Id INTEGER NOT NULL,
    FOREIGN KEY (Workout_Id) REFERENCES WORKOUTS(Id),
    FOREIGN KEY (Exercise_Id) REFERENCES EXERCISES(Id)
);
"""

SELECT_ALL_EXERCISES = "SELECT * FROM EXERCISES;"
SELECT_EXERCISE_BY_ID = "SELECT * FROM EXERCISES WHERE Id = ?;"
INSERT_EXERCISE = "INSERT INTO EXERCISES (Name, Type, Muscle, Equipment, Difficulty, Instructions) VALUES (?, ?, ?, ?, ?, ?);"

SELECT_ALL_EXERCISE_SETS = "SELECT * FROM EXERCISE_SETS;"
SELECT_EXERCISE_SET_BY_ID = "SELECT * FROM EXERCISE_SETS WHERE Id = ?;"
INSERT_EXERCISE_SET = "INSERT INTO EXERCISE_SETS (Exercise_Id, Sets, Reps, SetOrder) VALUES (?, ?, ?, ?);"

SELECT_ALL_WORKOUTS = "SELECT Id, Title, Color, Type, Description FROM WORKOUTS;"
SELECT_WORKOUT_BY_ID = "SELECT Id, Title, Color, Type, Description FROM WORKOUTS WHERE Id = ?;"
INSERT_WORKOUT = "INSERT INTO WORKOUTS (Title, Color, Type, Description) VALUES (?, ?, ?, ?);"
UPDATE_WORKOUT_BY_ID = "UPDATE WORKOUTS SET Title = ?, Color = ?, Type = ?, Description = ? WHERE Id = ?;"

SELECT_ALL_WORKOUT_EXERCISE_SETS = "SELECT * FROM WORKOUT_EXERCISE_SETS;"
SELECT_WORKOUT_EXERCISE_SET_BY_ID = "SELECT * FROM WORKOUT_EXERCISE_SETS WHERE Id = ?;"
INSERT_WORKOUT_EXERCISE_SET = "INSERT INTO WORKOUT_EXERCISE_SETS (Workout_Id, Exercise_Id) VALUES (?, ?);"

SELECT_WORKOUT_DETAILS = """
SELECT w.Id, w.Title, w.Color, w.Type, w.Description,
       e.Id, e.Name, e.Type, e.Muscle, e.Equipment, e.Difficulty, e.Instructions,
       es.Sets, es.Reps, es.SetOrder
FROM WORKOUTS w
LEFT JOIN WORKOUT_EXERCISE_SETS wes ON w.Id = wes.Workout_Id
LEFT JOIN EXERCISES e ON wes.Exercise_Id = e.Id
LEFT JOIN EXERCISE_SETS es ON e.Id = es.Exercise_Id
WHERE w.Id = ?
ORDER BY es.SetOrder;
"""

INSERT_WORKOUT_EXERCISE_SET = """
INSERT INTO WORKOUT_EXERCISE_SETS (Workout_Id, Exercise_Id)
VALUES (?, ?);
"""

DROP_DATE_TIME_COLUMNS = [
    "PRAGMA foreign_keys=off;",
    "BEGIN TRANSACTION;",
    """
    CREATE TABLE IF NOT EXISTS WORKOUTS_NEW (
        Id INTEGER PRIMARY KEY AUTOINCREMENT,
        Title TEXT NOT NULL,
        Color TEXT,
        Type TEXT,
        Description TEXT
    );
    """,
    """
    INSERT INTO WORKOUTS_NEW (Id, Title, Color, Type, Description)
    SELECT Id, Title, Color, NULL, NULL
    FROM WORKOUTS;
    """,
    "DROP TABLE WORKOUTS;",
    "ALTER TABLE WORKOUTS_NEW RENAME TO WORKOUTS;",
    "COMMIT;",
    "PRAGMA foreign_keys=on;"
]